name: CI/CD - Sistema MusicADJ

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do código
        uses: actions/checkout@v3

      - name:  Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name:  Instalar dependências
        run: npm install

      - name:  Executar testes (via Node)
        run: node ./node_modules/jest/bin/jest.js --ci --runInBand

      - name:  Deploy automático no Railway
        if: success()
        env:
          RAILWAY_DEPLOY_HOOK: ${{ secrets.RAILWAY_DEPLOY_HOOK }}
        run: |
          echo "Chamando o deploy automático no Railway..."
          curl -X POST "$RAILWAY_DEPLOY_HOOK"
