name: CI/CD - Sistema MusicADJ (Render)

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configurar o Node.js (versão 18)
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instalar dependências do projeto
      - name: Instalar dependências
        run: npm install

      # Executar testes automatizados com Jest
      - name: Executar testes automatizados
        run: node ./node_modules/jest/bin/jest.js --ci --runInBand

      #  Deploy automático no Render
      - name: Deploy automático no Render
        if: success()
        run: |
          echo "Chamando o deploy automático no Render..."
          curl -X POST "https://api.render.com/deploy/srv-d498h5hr0fns738ejvu0?key=ziGBDxN9I5A"
